# Generated by Django 4.0.2 on 2022-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=True)),
                ('time', models.TimeField(default=True)),
                ('camera', models.CharField(max_length=20)),
                ('speed', models.FloatField()),
                ('number_plate', models.TextField(default=True, max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
    ]
