# Generated by Django 4.0.2 on 2022-06-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_camera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.AlterField(
            model_name='vehiclespeed',
            name='date',
            field=models.DateField(blank=True, default=True, null=True),
        ),
    ]
